Repository Shopify/ui-extensions, pull requests merged in 2022-07, with the labels that each got.

#394 Remove the `checkout_extensions` feature flag from generated checkout UI pages
  scripts/generate-docs-checkout.ts
Labels: #gsd:23421

#395 Improve comments for values of unions
  package.json
  packages/checkout-ui-extensions/src/components/Banner/README.md
  packages/checkout-ui-extensions/src/components/Button/README.md
  packages/checkout-ui-extensions/src/components/Icon/README.md
  packages/checkout-ui-extensions/src/components/SkeletonText/README.md
  packages/checkout-ui-extensions/src/components/SkeletonTextBlock/README.md
  packages/checkout-ui-extensions/src/components/Text/README.md
  packages/checkout-ui-extensions/src/components/TextBlock/README.md
  scripts/typedoc/shopify-dev-renderer/shared/index.ts
  yarn.lock
Labels: bug

#401 Add GraphQL endpoint to extension API
  packages/customer-account-ui-extensions-react/src/render.tsx
  packages/customer-account-ui-extensions/src/extension-points/extension-points.ts
  packages/customer-account-ui-extensions/src/extension-points/index.ts
  packages/customer-account-ui-extensions/src/extension-points/standard-api.ts
Labels: gsd:23677
