Repository Shopify/ui-extensions, pull requests merged in 2024-05, with the labels that each got.

#1969 Added buyer_accepts_sms_marketing to wpm
  packages/web-pixels-extension/src/schemas/pixel-events.ts
  packages/web-pixels-extension/src/types/PixelEvents/index.ts
Labels: #gsd:40571

#1976 Add troubleshooting doc and examples
  packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/troubleshooting/api-component-not-working.txt
  packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/troubleshooting/cannot-be-used-as-jsx.txt
  packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/troubleshooting/could-not-resolve.txt
  packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/troubleshooting/site-unreachable.txt
  packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/troubleshooting/unable-to-access.txt
  packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/pages/troubleshooting.doc.ts
Labels: documentation

#2022 update number and email field docs
  packages/ui-extensions/docs/surfaces/point-of-sale/reference/components/EmailField.doc.ts
  packages/ui-extensions/docs/surfaces/point-of-sale/reference/components/NumberField.doc.ts
  packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/email-field/email-input.ts
  packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/email-field/email-input.tsx
  packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/number-field/number-input.ts
  packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/number-field/number-input.tsx
  packages/ui-extensions/src/surfaces/point-of-sale/components/NumberField/NumberField.ts
Labels: #gsd:37689
