Repository Shopify/ui-extensions, pull requests merged in 2025-09, with the labels that each got.

#3207 Update Customer account component images
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/avatar-preview.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/avatar-thumbnail.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/buttongroup-preview.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/buttongroup-thumbnail.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/card-preview.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/card-thumbnail.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/customeraccountaction-preview.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/customeraccountaction-thumbnail.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/imagegroup-preview.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/imagegroup-thumbnail.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/menu-preview.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/menu-thumbnail.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/page-preview.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/page-thumbnail.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/resourceitem-preview.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/resourceitem-thumbnail.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/section-preview.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/section-thumbnail.png
  packages/ui-extensions/src/surfaces/customer-account/components/Avatar/Avatar.doc.ts
  packages/ui-extensions/src/surfaces/customer-account/components/CustomerAccountAction/CustomerAccountAction.doc.ts
  packages/ui-extensions/src/surfaces/customer-account/components/CustomerAccountAction/examples/basic-CustomerAccountAction-preact.example.tsx
  packages/ui-extensions/src/surfaces/customer-account/components/ImageGroup/ImageGroup.doc.ts
  packages/ui-extensions/src/surfaces/customer-account/components/ImageGroup/examples/basic-ImageGroup-js.example.ts
  packages/ui-extensions/src/surfaces/customer-account/components/ImageGroup/examples/basic-ImageGroup-preact.example.tsx
  packages/ui-extensions/src/surfaces/customer-account/components/Menu/Menu.doc.ts
  packages/ui-extensions/src/surfaces/customer-account/components/Page/Page.doc.ts
  packages/ui-extensions/src/surfaces/customer-account/components/Page/examples/basic-Page-preact.example.tsx
  packages/ui-extensions/src/surfaces/customer-account/components/Section/Section.doc.ts
Labels: #gsd:42886

#3210 Update Customer account examples to use signals instead of hooks
  .changeset/itchy-nails-wave.md
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/apis/analytics-publish.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/apis/analytics-visitor.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/apis/attribute-values.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/apis/authenticated-account-company-and-location.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/apis/authenticated-account.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/apis/cart-line-item.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/apis/customer-account-api-fetch.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/apis/customer-privacy.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/apis/localization-country.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/apis/query-fetch.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/apis/query.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/apis/require-login.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/apis/session-token.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/apis/settings-access.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/apis/translate-pluralization.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/apis/translate.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/reference/examples/navigation/default-preact.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/staticPages/examples/extension-apis-preact.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/staticPages/examples/extension-targets-preact.example.tsx
  packages/ui-extensions/docs/surfaces/customer-account/staticPages/examples/form-default-value.jsx
  packages/ui-extensions/docs/surfaces/customer-account/staticPages/examples/form-implicit-default.jsx
  packages/ui-extensions/docs/surfaces/customer-account/staticPages/examples/ui-components-preact.example.tsx
  packages/ui-extensions/src/surfaces/customer-account/components/Avatar/examples/basic-Avatar-preact.example.tsx
  packages/ui-extensions/src/surfaces/customer-account/components/ButtonGroup/examples/basic-ButtonGroup-preact.example.tsx
  packages/ui-extensions/src/surfaces/customer-account/components/CustomerAccountAction/examples/basic-CustomerAccountAction-preact.example.tsx
  packages/ui-extensions/src/surfaces/customer-account/components/ImageGroup/examples/basic-ImageGroup-preact.example.tsx
  packages/ui-extensions/src/surfaces/customer-account/components/Menu/examples/basic-Menu-preact.example.tsx
  packages/ui-extensions/src/surfaces/customer-account/components/Page/examples/basic-Page-preact.example.tsx
  packages/ui-extensions/src/surfaces/customer-account/components/Section/examples/basic-Section-preact.example.tsx
Labels: #gsd:42886

#3218 Add ColorField and ColorPicker docs
  packages/ui-extensions/docs/surfaces/admin/screenshots/components/color-field.png
  packages/ui-extensions/docs/surfaces/admin/screenshots/components/color-picker.png
  packages/ui-extensions/src/docs/shared/components/ColorField.ts
  packages/ui-extensions/src/docs/shared/components/ColorPicker.ts
  packages/ui-extensions/src/surfaces/admin/components/ColorField/ColorField.doc.ts
  packages/ui-extensions/src/surfaces/admin/components/ColorField/examples/default.html
  packages/ui-extensions/src/surfaces/admin/components/ColorPicker/ColorPicker.doc.ts
  packages/ui-extensions/src/surfaces/admin/components/ColorPicker/examples/default.html
Labels: #gsd:46280

#3215 Use ReadonlySignalLike type in Customer account
  .changeset/hot-cycles-grab.md
  packages/ui-extensions/src/surfaces/customer-account/api.ts
  packages/ui-extensions/src/surfaces/customer-account/api/cart-line/cart-line-item.ts
  packages/ui-extensions/src/surfaces/customer-account/api/order-status/order-status.ts
  packages/ui-extensions/src/surfaces/customer-account/api/shared.ts
  packages/ui-extensions/src/surfaces/customer-account/api/standard-api/standard-api.ts
  packages/ui-extensions/src/surfaces/customer-account/preact/subscription.ts
Labels: #gsd:42886

#3314 Update signal-like type in Customer account to have deprecated fields
  .changeset/empty-tigers-happen.md
  packages/ui-extensions/src/shared.ts
  packages/ui-extensions/src/surfaces/customer-account/api.ts
  packages/ui-extensions/src/surfaces/customer-account/api/cart-line/cart-line-item.ts
  packages/ui-extensions/src/surfaces/customer-account/api/order-status/order-status.ts
  packages/ui-extensions/src/surfaces/customer-account/api/shared.ts
  packages/ui-extensions/src/surfaces/customer-account/api/standard-api/standard-api.ts
  packages/ui-extensions/src/surfaces/customer-account/preact/subscription.ts
Labels: #gsd:42886

#3348 Update POS PWC component descriptions for consistent tone and voice
  packages/ui-extensions/src/surfaces/point-of-sale/components/Badge/Badge.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/Banner/Banner.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/Box/Box.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/Button/Button.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/ChoiceList/ChoiceList.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/Clickable/Clickable.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/DateField/DateField.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/DatePicker/DatePicker.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/DateSpinner/DateSpinner.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/EmailField/EmailField.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/Icon/Icon.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/Modal/Modal.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/NumberField/NumberField.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/Page/Page.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/PosBlock/PosBlock.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/ScrollBox/ScrollBox.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/SearchField/SearchField.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/Text/Text.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/TextArea/TextArea.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/TextField/TextField.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/Tile/Tile.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/TimeField/TimeField.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/TimePicker/TimePicker.doc.ts
Labels: #gsd:46363

#3362 [POS] Update Badge example and subsections
  packages/ui-extensions/src/surfaces/point-of-sale/components/Badge/Badge.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/Badge/examples/default.html
Labels: #gsd:46363

#3357 Update component images in Customer account
  .changeset/lazy-kings-cry.md
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/avatar-default.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/avatar-preview.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/avatar-thumbnail.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/buttongroup-default.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/buttongroup-preview.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/buttongroup-thumbnail.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/customeraccountaction-default.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/customeraccountaction-preview.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/customeraccountaction-thumbnail.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/imagegroup-default.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/imagegroup-preview.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/imagegroup-thumbnail.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/menu-default.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/menu-preview.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/menu-thumbnail.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/page-default.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/page-preview.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/page-thumbnail.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/section-default.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/section-preview.png
  packages/ui-extensions/docs/surfaces/customer-account/screenshots/section-thumbnail.png
  packages/ui-extensions/src/surfaces/customer-account/components/Avatar/Avatar.doc.ts
  packages/ui-extensions/src/surfaces/customer-account/components/Avatar/examples/basic-Avatar.example.html
  packages/ui-extensions/src/surfaces/customer-account/components/ButtonGroup/ButtonGroup.doc.ts
  packages/ui-extensions/src/surfaces/customer-account/components/CustomerAccountAction/CustomerAccountAction.doc.ts
  packages/ui-extensions/src/surfaces/customer-account/components/CustomerAccountAction/examples/basic-CustomerAccountAction.example.html
  packages/ui-extensions/src/surfaces/customer-account/components/ImageGroup/ImageGroup.doc.ts
  packages/ui-extensions/src/surfaces/customer-account/components/Menu/Menu.doc.ts
  packages/ui-extensions/src/surfaces/customer-account/components/Page/Page.doc.ts
  packages/ui-extensions/src/surfaces/customer-account/components/Section/Section.doc.ts
Labels: #gsd:42886

#3401 POS: add Divider docs for 2025-10
  packages/ui-extensions/src/surfaces/point-of-sale/components/Divider/Divider.doc.ts
  packages/ui-extensions/src/surfaces/point-of-sale/components/Divider/examples/default.html
Labels: #gsd:46363

#3429 Update Customer account docs to reflect 2025-10 setup
  packages/ui-extensions/docs/surfaces/customer-account/staticPages/examples/scaffolding.example.bash
  packages/ui-extensions/docs/surfaces/customer-account/staticPages/examples/upgrading-to-2025-10-rc/package-json-new.json
Labels: #gsd:42886
